# frontend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: retro-arcade-frontend
  labels:
    app: retro-arcade-hub
    component: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: retro-arcade-hub
      component: frontend
  template:
    metadata:
      labels:
        app: retro-arcade-hub
        component: frontend
    spec:
      containers:
        - name: frontend-app
          # Updated to the new image tag you just built
          image: quay.io/rhn_support_rbobek/retro-arcade-hub-frontend:1.0.3
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 1

